spring.application.name=eventapp
spring.datasource.url=jdbc:mysql://localhost:3306/eventapp
spring.datasource.username=eusebiu
spring.datasource.password=pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect